### PR TITLE
Prettier formatting

### LINKED ISSUE #29: Proposal: New format for fzf items
Hi!

Love the plugin. I prefer fzf over telescope, so it's great to have functionality like this for LSP. However, Telescope does have some UI niceties that I have included in a local patch.

I was wondering if you are interested in including the patch.

## Changes

- don't include the file path in window or let you fzf on it.

  I found the file path crowed the results, and sort of defeated the purpose of the window. I would just use normal `:Files` if i wanted to match on the file path.

- organize the symbol and the "kind" into columns, truncating the symbol if it's too long.
- colorize the "kind". this allows easier visual recognition of the type of symbol you are looking at

image

I am open to critique on any of my changes, or added config options to customize anything.

One other thing I am going to try and add is treesitter highlighting the symbols before they are fed to fzf. This would require creating an ansi highlighter using the neovim treesitter api, but shouldn't be too difficult.

Let me know what you think! Thanks

### PR DESCRIPTION
**Pull request by mhanberg**
## Description

- adds dependency on plenary.nvim
- vendors ansicolors.lua
- colors symbol kind
- formats line and symbol into columns
- hides the file path and doesn't fuzzy match on it

Fixes #29

## Notes

- Any type of feedback is welcome 😄.

### CODE REVIEW

**Comment by gfanto** [comment]
Thanks for the PR, i look at it and looks good to me, the only thing i would like to have it's an option to enable/disable the "prittier formatting", what you think about that?

**Comment by mhanberg** [comment]
I don't think a "enable/disable" is a good config opt to add, but another avenue could be to allow the user to provide a function to customize the formatting to whatever they want.

**Comment by mhanberg** [comment]
And could also expose two functions, the one that this PR implements and a "plain" one that retains the old behavior.

**Comment by gfanto** [comment]
Yeah sounds good, i was thinking on a "fast" change to merge the PR.
I think we can merge this PR and see if someone complain for the change on formatting (i don't think it will happen, but this was my reason on asking you the option stuff), then in case we can make the changes to have both the old and the new behavior.

**Review by gfanto — APPROVED** [review]
LGTM well done! ❤️

**Comment by mhanberg** [comment]
Thank you! Feel free to merge 👍.

**Comment by mhanberg** [comment]
@gfanto probably need to update the gif in the readme now 😄 .

**Comment by gfanto** [comment]
Ehehehe good point! I've updated it right now :v:

**Comment by aljoscha** [comment]
Just noticed this after updating my packages. Could we add an option for getting back the file path? I find it very helpful to know what file references are coming from, for example for `:References`.

**Comment by mhanberg** [comment]
@aljoscha I opened a proposal for this that I'll get to implementing soon (given we reach a decision on the right direction) #31

**Comment by gfanto** [comment]
@aljoscha @mhanberg I've made a fast fix now with a new option to allow you to enable/disable the "pretty formatting"
The default is set to the old version and to enable the "pretty formatting" you have to add the configuration `let g:fzf_lsp_pretty = v:true`

**Comment by aljoscha** [comment]
Thanks a lot for the prompt response to this! :blush:

**Pull request merged**
